---
name: main

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Test noop IO
        run: npm test
        env:
          CURATOR_IO: noop
          CURATOR_PKG: noop
      - name: Test linux IO
        run: npm test
        env:
          CURATOR_IO: linux
          CURATOR_PKG: noop
